sudo: required

services:
          - docker

install:
        - sudo apt-get install gawk
        - docker build -t toredash/docker-teamspeak3 .
        - docker run --detach -p 9987:9987/udp -p 30033:30033 -p 10011:10011 -p 41144:41144 toredash/docker-teamspeak3
        - docker ps -a
        - sleep 5


script:
        - bash travis/test.sh
