sudo: required

services:
          - docker

install:
        - docker build -t toredash/docker-teamspeak3 .
        - sudo apt-get install netcat

script:
        - bash travis/test.sh
          # Testing that logs er persistent
        - bash travis/log-testing.sh
